### ISSUE TITLE
nihao 

### ISSUE THREAD

**Issue by vTNT** [527593036/AnsiApi#1]
有木有计划支持ansible 2.0的 api呢

**Comment by vTNT** [comment]
ANSIBLE_HOSTS_LIST = PATH + "/inventory.sh"
你好 这个sh文件 能否分享下

**Comment by 527593036** [comment]
有计划，但是短期内还不会支持

这个是动态的inventory的脚本，应用场景不一样，脚本也不一样，可参考官方文档
http://docs.ansible.com/ansible/developing_inventory.html

**Comment by 527593036** [comment]
@vTNT 

有计划，但是短期内还不会支持

这个是动态的inventory的脚本，应用场景不一样，脚本也不一样，可参考官方文档
http://docs.ansible.com/ansible/developing_inventory.html

**Comment by vTNT** [comment]
hao d
